"""add driver phone number

Revision ID: 23d4af767c54
Revises: ecd8ebb42df5
Create Date: 2026-05-19 23:48:49.190205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23d4af767c54'
down_revision: Union[str, Sequence[str], None] = 'ecd8ebb42df5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver', 'phone_number')
    # ### end Alembic commands ###
